import type {
  LedgerDetail,
  LedgerConfig,
} from "../../../../domain/ledger/types";
export const now = "2026-10-07T13:02:00+08:00";
export const row: LedgerDetail = {
  sessionId: "ui-session",
  agentSessionId: "ui-agent",
  title: "OpenAPI 文档生成器",
  projectRoot: "/project/keepline",
  runtimeId: "claude-code",
  state: "running",
  possiblyWaiting: false,
  available: true,
  asks: [
    {
      id: "ask-1",
      text: "从 local-api 路由生成 OpenAPI 3.1 文档",
      authoredText: "从 local-api 路由生成 OpenAPI 3.1 文档",
      kind: "initial",
      at: "2026-10-07T12:05:00+08:00",
    },
  ],
  items: (["done", "doing", "todo"] as const).map((status, i) => ({
    id: `item-${i}`,
    ordinal: i,
    title: ["生成 API 文档", "检查 lint", "运行测试"][i],
    anchors: { paths: [], commands: [], keywords: [] },
    constraints: [],
    source: "user",
    status,
    statusSource: "rule",
    evidenceIds: status === "done" ? ["ev-1"] : [],
  })),
  evidence: [
    {
      id: "ev-1",
      kind: "test",
      callId: "call-1",
      at: "2026-10-07T13:01:00+08:00",
      value: "openapi lint · 0 错误",
      exitCode: 0,
    },
  ],
  trail: [
    {
      callId: "call-1",
      name: "exec",
      summary: "bun test openapi",
      at: "2026-10-07T13:01:00+08:00",
      turnId: "turn-1",
      itemId: "item-0",
      evidenceIds: ["ev-1"],
      violations: [],
      acceptedOffPlan: false,
    },
  ],
  readOnlyCount: 4,
  turns: [
    {
      id: "turn-1",
      at: "2026-10-07T12:05:00+08:00",
      phase: "started",
      readOnlyCount: 4,
      durationMs: 3000000,
    },
  ],
  offPlan: [],
  claims: [{ text: "lint 通过", evidenceIds: ["ev-1"] }],
  acceptances: [],
  progress: { done: 1, total: 3 },
  lastActiveAt: "2026-10-07T13:01:00+08:00",
  turnId: "turn-1",
  activity: {
    action: "正在写 scripts/openapi.ts",
    at: "2026-10-07T13:01:00+08:00",
    lastMessage: "先把 recovery 路由生成出来",
    evidence: [
      {
        id: "ev-1",
        kind: "test",
        callId: "call-1",
        at: "2026-10-07T13:01:00+08:00",
        value: "openapi lint · 0 错误",
        exitCode: 0,
      },
    ],
  },
};
export const settings: LedgerConfig = {
  enabled: true,
  retentionDays: 30,
  stalledAfterSeconds: 900,
  alertCoalesceSeconds: 600,
  judge: { enabled: false, backend: "cli-claude", model: null },
  deviation: "conservative",
  constraints: true,
  alerts: {
    needs_input: true,
    off_plan: false,
    claimed_unverified: false,
    stalled: false,
    limited: false,
  },
  nativeNotifications: true,
  focus: { minutes: 30, until: null },
  staleGoalDays: 7,
  exclude: { projects: [], runtimes: [] },
};
